import { Activity, AlertTriangle, BarChart3, Map, ShieldAlert, Users } from "lucide-react";
import { CivicPageHeader, DemoNote, GlassCard, Metric } from "./civic-ui";

const modules = {
  projects: ["Projects", "Project portfolio", "Monitor delivery milestones, verified progress, and exceptions across the active portfolio.", "248", "Active projects", "75% on-track delivery"],
  prediction: ["AI intelligence", "Prediction center", "Demo projections combine reported progress with available verification signals.", "82/100", "Risk score", "81% delay probability"],
  analytics: ["Portfolio intelligence", "Project analytics", "Compare delivery progress, cost health, and regional performance trends.", "72%", "Portfolio progress", "6.4% ahead of last quarter"],
  verification: ["Evidence intelligence", "Progress verification", "Compare reported project progress with available visual and field evidence.", "14 pp", "Progress mismatch", "Field inspection recommended"],
  satellite: ["Geospatial intelligence", "Satellite intelligence", "Review large-scale construction activity, project locations, and before/after evidence.", "18", "Monitored locations", "4 new change detections"],
  contractors: ["Delivery partners", "Contractor performance", "Use performance indicators to focus review and support conversations.", "86", "Portfolio score", "12 contractors under review"],
  alerts: ["Early warning", "AI alerts", "Prioritized signals requiring review or a field action.", "6", "High priority", "31 active warnings"],
  complaints: ["Public accountability", "Complaints and disputes", "Track reported issues through verification, assignment, and resolution.", "47", "Open complaints", "14 awaiting assignment"],
  settings: ["Workspace", "Authority settings", "Manage notification preferences, dashboard views, and workspace controls.", "3", "Active teams", "Demo workspace configuration"],
} as const;

export function AuthorityModule({ module }: { module: keyof typeof modules }) {
  const [eyebrow, title, description, value, label, detail] = modules[module];
  const Icon = module === "satellite" ? Map : module === "alerts" ? AlertTriangle : module === "contractors" ? Users : module === "analytics" || module === "verification" ? BarChart3 : module === "prediction" ? ShieldAlert : Activity;
  return <div className="mx-auto max-w-7xl space-y-6"><CivicPageHeader action={module === "complaints" ? "Assign complaint" : "Export view"} description={description} eyebrow={eyebrow} title={title} /><DemoNote /><div className="grid gap-4 md:grid-cols-3"><Metric detail={detail} label={label} tone={module === "alerts" || module === "prediction" ? "rose" : "blue"} value={value} /><GlassCard className="p-5 md:col-span-2"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-teal-400/10 text-teal-300"><Icon className="size-5" /></span><div><h2 className="font-semibold text-white">Operational insight</h2><p className="mt-1 text-sm text-slate-400">Review the latest portfolio indicators and take the appropriate next action.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Reported progress", "Verified evidence", "Recommended action"].map((item, index) => <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4" key={item}><p className="text-xs text-slate-500">{item}</p><p className="mt-2 font-semibold text-slate-100">{index === 0 ? "72%" : index === 1 ? "58%" : "Review now"}</p></div>)}</div></GlassCard></div><GlassCard className="overflow-hidden"><div className="border-b border-white/10 px-5 py-4"><h2 className="font-semibold text-white">Priority review queue</h2></div><div className="divide-y divide-white/10">{["NH-44 Corridor Upgrade", "Bengaluru Metro Phase II", "Coastal Water Supply Scheme"].map((item, index) => <div className="flex items-center justify-between gap-4 px-5 py-4" key={item}><div><p className="text-sm font-medium text-slate-100">{item}</p><p className="mt-1 text-xs text-slate-500">Demo record · Updated today</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${index === 0 ? "bg-rose-400/10 text-rose-300" : "bg-blue-400/10 text-blue-300"}`}>{index === 0 ? "Needs review" : "Monitoring"}</span></div>)}</div></GlassCard></div>;
}
