import { AlertTriangle, ClipboardCheck, FolderKanban, MessageSquareWarning } from "lucide-react";
import { ProgressBar, RiskBadge, SectionCard, SectionHeading, StatCard, StatusBadge } from "@/components/dashboard/dashboard-ui";
import { authorityStats, dashboardAlerts, priorityProjects } from "@/lib/mock-dashboard-data";

const statIcons = [FolderKanban, ClipboardCheck, AlertTriangle, MessageSquareWarning];

export default function DashboardPage() {
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Authority dashboard</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Infrastructure overview</h1><p className="mt-2 text-sm text-slate-600">A consolidated view of project delivery, risks, and public issues.</p></div><span className="w-fit rounded-full bg-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">Demo data - not live government records</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{authorityStats.map((stat, index) => <StatCard icon={statIcons[index]} key={stat.label} {...stat} />)}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(320px,0.8fr)]"><SectionCard className="overflow-hidden"><SectionHeading action="View all projects" title="Priority projects" /><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-left"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Project</th><th className="px-5 py-3">Progress</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Risk</th></tr></thead><tbody className="divide-y divide-slate-100">{priorityProjects.map((project) => <tr className="hover:bg-slate-50" key={project.id}><td className="px-5 py-4"><p className="font-semibold text-slate-800">{project.name}</p><p className="mt-1 text-xs text-slate-500">{project.id} · {project.region}</p></td><td className="w-48 px-5 py-4"><div className="flex justify-between text-xs font-medium text-slate-600"><span>{project.progress}% complete</span><span>{project.variance}</span></div><div className="mt-2"><ProgressBar value={project.progress} /></div></td><td className="px-5 py-4"><StatusBadge status={project.status} /></td><td className="px-5 py-4"><RiskBadge risk={project.risk} /></td></tr>)}</tbody></table></div></SectionCard><SectionCard><SectionHeading action="Open alerts" title="Needs attention" /><div className="divide-y divide-slate-100 px-5">{dashboardAlerts.map((alert) => <article className="py-4" key={alert.title}><div className="flex items-start gap-3"><span className={`mt-1 size-2 rounded-full ${alert.tone === "rose" ? "bg-rose-500" : alert.tone === "amber" ? "bg-amber-500" : "bg-blue-500"}`} /><div><h3 className="text-sm font-semibold text-slate-800">{alert.title}</h3><p className="mt-1 text-xs font-medium text-slate-500">{alert.project}</p><p className="mt-2 text-sm leading-5 text-slate-600">{alert.detail}</p></div></div></article>)}</div></SectionCard></div></div>;
}
